name: CI linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get all dependancies
      run: git submodule update --init --recursive

    - name: Configure And Build 
      run: cmake -S -DBUILD_GMOCK=OFF . -B build
    
    - name: Test
      run: cd build; make; ./tests/TempliTest  
