name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: install rcli 
      run: bash <(curl -s https://raw.githubusercontent.com/RickaPrincy/rcli/main/install.sh)

    - name: Get submodule dependancies
      run: git submodule update --init --recursive

    - name: Configure And Build 
      run: cmake  -DBUILD_GMOCK=OFF -S . -B build
    
    - name: Test
      run: cd build; make; ./bin/TempliTest  

  style:
    runs-on: ubuntu-latest
    name: check style 
    strategy:
      matrix:
        path:
          - 'sources'
          - 'include'
    steps:
    - uses: actions/checkout@v4
    
    - name: install rcli 
      run: bash <(curl -s https://raw.githubusercontent.com/RickaPrincy/rcli/main/install.sh)

    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '18'
        check-path: ${{ matrix.path }}
        fallback-style: 'Mozilla'
