name: CI linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get all dependancies
      run: git submodule update --init --recursive

    - name: Configure And Build 
      run: sh ./configure_and_build.sh
    
    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ./Templi_test

