name: CI linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: install rcli 
      run: bash <(curl -s https://raw.githubusercontent.com/RickaPrincy/rcli/main/install.sh)

    - name: Get submodule dependancies
      run: git submodule update --init --recursive

    - name: Configure And Build 
      run: cmake  -DBUILD_GMOCK=OFF -S . -B build
    
    - name: Test
      run: cd build; make; ./tests/TempliTest  
