name: ci 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install cpp_inquirer 
      run: bash <(curl -s https://raw.githubusercontent.com/RickaPrincy/cpp_inquirer/main/install.sh)

    - name: install rcli 
      run: bash <(curl -s https://raw.githubusercontent.com/RickaPrincy/rcli/main/install.sh)

    - name: Get submodule dependancies
      run: git submodule update --init --recursive

    - name: Configure And Build 
      run: cmake  -DBUILD_GMOCK=OFF -S . -B build
    
    - name: Run Clang-Format check target 
      run: cmake --build build --target format-check
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install cpp_inquirer 
      run: bash <(curl -s https://raw.githubusercontent.com/RickaPrincy/cpp_inquirer/main/install.sh)
    
    - name: install rcli 
      run: bash <(curl -s https://raw.githubusercontent.com/RickaPrincy/rcli/main/install.sh)

    - name: Get submodule dependancies
      run: git submodule update --init --recursive

    - name: Configure And Build 
      run: cmake  -DBUILD_GMOCK=OFF -S . -B build
    
    - name: Test
      run: |
        export LD_LIBRARY_PATH=/usr/local/lib:\$LD_LIBRARY_PATH
        cd build; make; cd tests/bin; ./TempliTest  
