name: CI linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get submodule dependancies
      run: git submodule update --init --recursive

    - name: Configure And Build 
      run: cmake  -DBUILD_GMOCK=OFF -S . -B build
    
    - name: Test
      run: cmake --build build --target format-check
